# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rand_param.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 758)
        MainWindow.setMinimumSize(QtCore.QSize(894, 606))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_tunes = QtWidgets.QPushButton(self.tab)
        self.pb_tunes.setObjectName("pb_tunes")
        self.verticalLayout.addWidget(self.pb_tunes)
        self.pb_chrom = QtWidgets.QPushButton(self.tab)
        self.pb_chrom.setObjectName("pb_chrom")
        self.verticalLayout.addWidget(self.pb_chrom)
        self.pb_oct = QtWidgets.QPushButton(self.tab)
        self.pb_oct.setEnabled(True)
        self.pb_oct.setObjectName("pb_oct")
        self.verticalLayout.addWidget(self.pb_oct)
        self.label_other = QtWidgets.QLabel(self.tab)
        self.label_other.setObjectName("label_other")
        self.verticalLayout.addWidget(self.label_other)
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout.addWidget(self.lineEdit_search)
        self.pb_search = QtWidgets.QPushButton(self.tab)
        self.pb_search.setObjectName("pb_search")
        self.verticalLayout.addWidget(self.pb_search)
        self.list_search = QtWidgets.QListWidget(self.tab)
        self.list_search.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_search.setObjectName("list_search")
        self.verticalLayout.addWidget(self.list_search)
        self.pb_search_add = QtWidgets.QPushButton(self.tab)
        self.pb_search_add.setObjectName("pb_search_add")
        self.verticalLayout.addWidget(self.pb_search_add)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_selected = QtWidgets.QLabel(self.tab)
        self.label_selected.setObjectName("label_selected")
        self.verticalLayout_4.addWidget(self.label_selected)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.pb_clear = QtWidgets.QPushButton(self.tab)
        self.pb_clear.setObjectName("pb_clear")
        self.verticalLayout_4.addWidget(self.pb_clear)
        self.label_bp = QtWidgets.QLabel(self.tab)
        self.label_bp.setObjectName("label_bp")
        self.verticalLayout_4.addWidget(self.label_bp)
        self.line_bp = QtWidgets.QLineEdit(self.tab)
        self.line_bp.setObjectName("line_bp")
        self.verticalLayout_4.addWidget(self.line_bp)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.label_n_points = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_n_points.sizePolicy().hasHeightForWidth())
        self.label_n_points.setSizePolicy(sizePolicy)
        self.label_n_points.setObjectName("label_n_points")
        self.horizontalLayout_4.addWidget(self.label_n_points)
        self.line_n_points = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_n_points.sizePolicy().hasHeightForWidth())
        self.line_n_points.setSizePolicy(sizePolicy)
        self.line_n_points.setObjectName("line_n_points")
        self.horizontalLayout_4.addWidget(self.line_n_points)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_generate = QtWidgets.QPushButton(self.tab_2)
        self.pb_generate.setObjectName("pb_generate")
        self.horizontalLayout_5.addWidget(self.pb_generate)
        self.pb_ref = QtWidgets.QPushButton(self.tab_2)
        self.pb_ref.setObjectName("pb_ref")
        self.horizontalLayout_5.addWidget(self.pb_ref)
        self.pb_optimize = QtWidgets.QPushButton(self.tab_2)
        self.pb_optimize.setEnabled(True)
        self.pb_optimize.setObjectName("pb_optimize")
        self.horizontalLayout_5.addWidget(self.pb_optimize)
        self.pb_load = QtWidgets.QPushButton(self.tab_2)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout_5.addWidget(self.pb_load)
        self.pb_save = QtWidgets.QPushButton(self.tab_2)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_5.addWidget(self.pb_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_5.addWidget(self.comboBox_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_waittime = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_waittime.sizePolicy().hasHeightForWidth())
        self.label_waittime.setSizePolicy(sizePolicy)
        self.label_waittime.setObjectName("label_waittime")
        self.horizontalLayout_6.addWidget(self.label_waittime)
        self.line_waittime = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_waittime.sizePolicy().hasHeightForWidth())
        self.line_waittime.setSizePolicy(sizePolicy)
        self.line_waittime.setObjectName("line_waittime")
        self.horizontalLayout_6.addWidget(self.line_waittime)
        self.check_simulate = QtWidgets.QCheckBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_simulate.sizePolicy().hasHeightForWidth())
        self.check_simulate.setSizePolicy(sizePolicy)
        self.check_simulate.setChecked(True)
        self.check_simulate.setObjectName("check_simulate")
        self.horizontalLayout_6.addWidget(self.check_simulate)
        self.pb_go = QtWidgets.QPushButton(self.tab_3)
        self.pb_go.setObjectName("pb_go")
        self.horizontalLayout_6.addWidget(self.pb_go)
        self.pb_revert = QtWidgets.QPushButton(self.tab_3)
        self.pb_revert.setAutoFillBackground(False)
        self.pb_revert.setObjectName("pb_revert")
        self.horizontalLayout_6.addWidget(self.pb_revert)
        self.pb_forward = QtWidgets.QPushButton(self.tab_3)
        self.pb_forward.setObjectName("pb_forward")
        self.horizontalLayout_6.addWidget(self.pb_forward)
        self.pb_stop = QtWidgets.QPushButton(self.tab_3)
        self.pb_stop.setObjectName("pb_stop")
        self.horizontalLayout_6.addWidget(self.pb_stop)
        self.pb_initial = QtWidgets.QPushButton(self.tab_3)
        self.pb_initial.setObjectName("pb_initial")
        self.horizontalLayout_6.addWidget(self.pb_initial)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_outfile = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_outfile.sizePolicy().hasHeightForWidth())
        self.label_outfile.setSizePolicy(sizePolicy)
        self.label_outfile.setObjectName("label_outfile")
        self.horizontalLayout_7.addWidget(self.label_outfile)
        self.line_outfile = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_outfile.sizePolicy().hasHeightForWidth())
        self.line_outfile.setSizePolicy(sizePolicy)
        self.line_outfile.setObjectName("line_outfile")
        self.horizontalLayout_7.addWidget(self.line_outfile)
        self.label_desc = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_desc.sizePolicy().hasHeightForWidth())
        self.label_desc.setSizePolicy(sizePolicy)
        self.label_desc.setObjectName("label_desc")
        self.horizontalLayout_7.addWidget(self.label_desc)
        self.line_desc = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_desc.sizePolicy().hasHeightForWidth())
        self.line_desc.setSizePolicy(sizePolicy)
        self.line_desc.setObjectName("line_desc")
        self.horizontalLayout_7.addWidget(self.line_desc)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layout_lifetime = QtWidgets.QVBoxLayout()
        self.layout_lifetime.setObjectName("layout_lifetime")
        self.verticalLayout_7.addLayout(self.layout_lifetime)
        self.pb_clear_lt = QtWidgets.QPushButton(self.tab_4)
        self.pb_clear_lt.setObjectName("pb_clear_lt")
        self.verticalLayout_7.addWidget(self.pb_clear_lt)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ranomd Trim Sequence"))
        self.pb_tunes.setText(_translate("MainWindow", "Add Tunes"))
        self.pb_chrom.setText(_translate("MainWindow", "Add Chroma"))
        self.pb_oct.setText(_translate("MainWindow", "Add Ocutpole"))
        self.label_other.setText(_translate("MainWindow", "Other:"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "LHCBEAM1/TRIM"))
        self.pb_search.setText(_translate("MainWindow", "Search"))
        self.pb_search_add.setText(_translate("MainWindow", "Add"))
        self.label_selected.setText(_translate("MainWindow", "Selected:"))
        self.pb_clear.setText(_translate("MainWindow", "Clear"))
        self.label_bp.setText(_translate("MainWindow", "Beam Process:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Parameter Selection"))
        self.label_n_points.setText(_translate("MainWindow", "Number of points:"))
        self.pb_generate.setText(_translate("MainWindow", "Generate trims"))
        self.pb_ref.setText(_translate("MainWindow", "Reference Trims"))
        self.pb_optimize.setText(_translate("MainWindow", "Optimize Sequence"))
        self.pb_load.setText(_translate("MainWindow", "Load Sequence"))
        self.pb_save.setText(_translate("MainWindow", "Save Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Random Generation"))
        self.label_waittime.setText(_translate("MainWindow", "Wait time (s): "))
        self.check_simulate.setText(_translate("MainWindow", "Simulate"))
        self.pb_go.setText(_translate("MainWindow", "Go !"))
        self.pb_revert.setText(_translate("MainWindow", "Revert"))
        self.pb_forward.setText(_translate("MainWindow", "Forward"))
        self.pb_stop.setText(_translate("MainWindow", "Stop"))
        self.pb_initial.setText(_translate("MainWindow", "Initial"))
        self.label_outfile.setText(_translate("MainWindow", "Output file"))
        self.label_desc.setText(_translate("MainWindow", "Description:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Trim Sequence"))
        self.pb_clear_lt.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Lifetime Feed"))

